# docker-compose.yml
services:
  goserver:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: high-performance-goserver
    ports:
      - "28999:28999"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    sysctls:
      net.core.somaxconn: 65535
      net.ipv4.tcp_max_syn_backlog: 65535
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "28999"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
